services:
  frontend:
    build:
      context: .
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    volumes:
      - .:/${COMPOSE_PROJECT_NAME}
    environment:
      NODE_ENV: ${FRONTEND_ENV}
    ports:
      - ${FRONTEND_PORT}:3000
      - ${FRONTEND_DEBUG_PORT}:9229

