services:
  frontend:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - bashlog:/home/node/bashlog
      - gh-config:/home/node/.config/gh
      - vscode-extensions:/home/node/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  bashlog:
  gh-config:
  vscode-extensions:
