services:
  frontend:
    build:
      context: .
      dockerfile: ./.devcontainer/vscode.Dockerfile
    volumes:
      - bashlog:/bashlog
      - vscode-extensions:/home/node/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  bashlog:
  vscode-extensions:
  